service: traceflow-app
runtime: custom

env_variables:
  INSTANCE_CONNECTION_NAME: "agorapolis:us-central1:traceflow-db"
  DB_NAME: "postgres"
  DB_USER: "traceflow_user"
  DB_PASSWORD: "5iwoxkMo"
  DEBUG: "False"
  DJANGO_SECRET_KEY: "django-insecure-replaceme-in-production"

automatic_scaling:
  min_instances: 0
  max_instances: 10

resources:
  memory_gb: 1
  cpu: 1
