# Generated by Django 4.2.27 on 2026-01-27 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('is_internal_book', models.BooleanField(default=False, help_text='True = General Ledger, False = Bank Statement')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negative for outflow, positive for inflow', max_digits=15)),
                ('description', models.TextField()),
                ('source_file', models.CharField(help_text="e.g., 'Chase_Dec_2023.pdf' or 'GL_2023.xlsx'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='forensics.account')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact Match'), ('FUZZY_DATE', 'Date Slippage'), ('FUZZY_DESCRIPTION', 'Description Match'), ('MANUAL', 'Manually Verified')], max_length=50)),
                ('confidence_score', models.FloatField(default=1.0, help_text='0.0 to 1.0, where 1.0 is absolute certainty')),
                ('notes', models.TextField(blank=True, help_text='Additional verification notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_transaction', models.ForeignKey(help_text='External evidence from bank statement', on_delete=django.db.models.deletion.CASCADE, related_name='bank_matches', to='forensics.transaction')),
                ('book_entry', models.ForeignKey(blank=True, help_text='Internal evidence from general ledger', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_matches', to='forensics.transaction')),
            ],
            options={
                'verbose_name': 'Reconciliation Match',
                'verbose_name_plural': 'Reconciliation Matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'amount'], name='forensics_t_date_ea08b8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date'], name='forensics_t_account_5ab464_idx'),
        ),
    ]
