# Generated by Django 4.2.27 on 2026-01-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ledger_journal_entry_uuid',
            field=models.UUIDField(blank=True, help_text='UUID of linked django-ledger JournalEntryModel', null=True),
        ),
    ]
