# Generated by Django 4.2.27 on 2026-01-28 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0002_transaction_ledger_journal_entry_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full Property/Park Name', max_length=255)),
                ('short_name', models.CharField(help_text='Property acronym (e.g., GCRV, PEM)', max_length=50)),
                ('base_property', models.CharField(help_text='Base Property code (GC, PEM, SPR, SR)', max_length=50)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='Unit/Lot number', max_length=50)),
                ('property_unit', models.CharField(help_text='Property_Unit (unique ID)', max_length=100, unique=True)),
                ('base_unit', models.CharField(help_text='Base Property and Unit # combination', max_length=100)),
                ('current_lhs_property', models.BooleanField(default=False, help_text='Currently owned by LHS or sold by LHS')),
                ('is_lhs_rental', models.BooleanField(default=False, help_text='LHS Rental unit')),
                ('is_rental_listed', models.BooleanField(default=False, help_text='Listed in Rental List')),
                ('bank_gl_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Total Bank GL Balance (Per Unit BS Report)', max_digits=15, null=True)),
                ('sale_amount_pre_tax', models.DecimalField(blank=True, decimal_places=2, help_text='Sale Amount (pre-tax)', max_digits=15, null=True)),
                ('sale_deposited_to', models.CharField(blank=True, help_text='Account where sale was deposited', max_length=255)),
                ('total_sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total Sale Price per PEM Sales Contract', max_digits=15, null=True)),
                ('gl_rental_income', models.DecimalField(blank=True, decimal_places=2, help_text='GL Rental Income (Credits)', max_digits=15, null=True)),
                ('gl_unearned_rent', models.DecimalField(blank=True, decimal_places=2, help_text='GL - Credits to Unearned Rent/Prepaid', max_digits=15, null=True)),
                ('gl_rental_deposits', models.DecimalField(blank=True, decimal_places=2, help_text='GL Rental Deposits', max_digits=15, null=True)),
                ('market_rental', models.DecimalField(blank=True, decimal_places=2, help_text='Market Rental Rate', max_digits=10, null=True)),
                ('current_occupant', models.CharField(blank=True, help_text='Current Occupant name', max_length=255)),
                ('address', models.CharField(blank=True, help_text='Unit address', max_length=500)),
                ('mco_owner_matches', models.BooleanField(blank=True, help_text='MCO Owner Matches Property Name?', null=True)),
                ('mco_owner', models.CharField(blank=True, help_text='MCO - Owner name', max_length=255)),
                ('mco_date_ref', models.CharField(blank=True, help_text='MCO Date and Invoice Reference', max_length=255)),
                ('duplicate_mco', models.BooleanField(default=False, help_text='Duplicate MCO (2nd version exists)')),
                ('mco_lot_mismatch', models.BooleanField(default=False, help_text='Lot/Unit on invoice does not match')),
                ('builder_invoice_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Builder Invoice Amount', max_digits=15, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Unit Serial Number', max_length=100)),
                ('builder_invoice_date', models.DateField(blank=True, help_text='Builder Invoice Date', null=True)),
                ('builder_ship_date', models.DateField(blank=True, help_text='Builder Ship Date', null=True)),
                ('bill_to', models.CharField(blank=True, help_text='Bill To party', max_length=255)),
                ('builder', models.CharField(blank=True, help_text='Builder name', max_length=255)),
                ('has_commissions', models.BooleanField(default=False, help_text='Has recorded commissions')),
                ('observations', models.TextField(blank=True, help_text='Forensic observations and notes')),
                ('cavco_champion_total', models.DecimalField(blank=True, decimal_places=2, help_text='Cavco/Champion/CMH total', max_digits=15, null=True)),
                ('mco_not_match', models.BooleanField(default=False, help_text='MCO does not match')),
                ('mco_indicates_home_sale_entity', models.BooleanField(default=False, help_text='MCO indicates Home Sale Entity as Owner')),
                ('commission_but_no_sale', models.BooleanField(default=False, help_text='Commission recorded but no sale identified')),
                ('no_mco_available', models.BooleanField(default=False, help_text='No MCO available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.CharField(help_text='Source CSV filename', max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='forensics.property')),
            ],
            options={
                'verbose_name': 'Inventory Unit',
                'verbose_name_plural': 'Inventory Units',
                'ordering': ['property', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Commission amount', max_digits=15)),
                ('recipient', models.CharField(help_text='Commission recipient (e.g., SBR, Ernesto)', max_length=255)),
                ('memo', models.TextField(blank=True, help_text='Memo / Invoice Number')),
                ('status', models.CharField(choices=[('SUPPORTED', 'Supported'), ('UNSUPPORTED', 'Unsupported'), ('INSUFFICIENT', 'Insufficient Evidence')], default='SUPPORTED', max_length=50)),
                ('comments', models.TextField(blank=True, help_text='Additional comments')),
                ('percentage_of_sales', models.DecimalField(blank=True, decimal_places=2, help_text='% of Sales Price', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='forensics.inventoryunit')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-amount'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryunit',
            index=models.Index(fields=['property', 'unit_number'], name='forensics_i_propert_4fad9e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryunit',
            index=models.Index(fields=['property_unit'], name='forensics_i_propert_a7b9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryunit',
            index=models.Index(fields=['current_lhs_property'], name='forensics_i_current_991a99_idx'),
        ),
    ]
