# Generated by Django 4.2.27 on 2026-01-28 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0003_property_inventoryunit_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliationmatch',
            name='bank_transaction',
        ),
        migrations.RemoveField(
            model_name='reconciliationmatch',
            name='book_entry',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='ReconciliationMatch',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
