# Generated by Django 4.2.27 on 2026-01-29 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0004_remove_old_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TAX', 'Tax Return'), ('BANK', 'Bank Statement'), ('INVOICE', 'Invoice')], help_text='Type of document', max_length=50)),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('tax_year', models.IntegerField(blank=True, help_text='Tax year (for tax documents)', null=True)),
                ('tax_type', models.CharField(blank=True, help_text='Type of tax return (e.g., 1040, 1120, K-1)', max_length=100)),
                ('statement_year', models.IntegerField(blank=True, help_text='Year (for bank statements)', null=True)),
                ('statement_month', models.IntegerField(blank=True, choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], help_text='Month (1-12)', null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name', max_length=255)),
                ('account_number', models.CharField(blank=True, help_text='Bank account number (partially masked)', max_length=100)),
                ('invoice_number', models.CharField(blank=True, help_text='Invoice number', max_length=100)),
                ('vendor_name', models.CharField(blank=True, help_text='Vendor/Supplier name', max_length=255)),
                ('invoice_date', models.DateField(blank=True, help_text='Invoice date', null=True)),
                ('invoice_year', models.IntegerField(blank=True, help_text='Year (for filtering)', null=True)),
                ('file_name', models.CharField(blank=True, help_text='Original file name', max_length=255)),
                ('file_path', models.CharField(blank=True, help_text='Path to document file', max_length=500)),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, help_text='File size in MB', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.CharField(blank=True, help_text='User who uploaded the document', max_length=255)),
                ('property', models.ForeignKey(blank=True, help_text='Related property', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='forensics.property')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type', 'property'], name='forensics_d_documen_88c47c_idx'), models.Index(fields=['tax_year'], name='forensics_d_tax_yea_a590cf_idx'), models.Index(fields=['statement_year', 'statement_month'], name='forensics_d_stateme_23b958_idx')],
            },
        ),
    ]
