# Generated by Django 4.2.27 on 2026-01-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='builder_pdf_filename',
            field=models.CharField(blank=True, help_text='Builder PDF Filename', max_length=500),
        ),
    ]
