# Generated by Django 5.2.7 on 2026-02-05 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0006_inventoryunit_builder_pdf_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gcs_path',
            field=models.CharField(blank=True, help_text='Path in GCP Cloud Storage (gs://bucket/path/to/file)', max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='inventory_unit',
            field=models.ForeignKey(blank=True, help_text='Associated inventory unit (for builder invoices)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='forensics.inventoryunit'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('TAX', 'Tax Return'), ('BANK', 'Bank Statement'), ('INVOICE', 'Invoice'), ('BUILDER_INVOICE', 'Builder Invoice')], help_text='Type of document', max_length=50),
        ),
    ]
