# Generated by Django 4.2.27 on 2026-02-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forensics', '0008_add_gcs_url_and_size_to_document'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='forensics_d_invento_idx',
        ),
    ]
